#!/bin/bash

path=$( dirname -- "$0"; )

FILE=$path/py2
if test -f "$FILE"; then
    echo "$FILE exists."
fi
FILE=$path/c
if test -f "$FILE"; then
    echo "$FILE exists."
fi
FILE=$path/cc
if test -f "$FILE"; then
    echo "$FILE exists."
fi
FILE=/compare/cc
if test -f "$FILE"; then
    echo "$FILE exists."
fi
FILE=/compare/cc
if test -f "$FILE"; then
    echo "$FILE exists."
fi

echo "ls"
ls

chmod a+x $path/py2

$path/py2 $3 $2 $1

if [ "$?" == "0" ]
then
  echo "AC"
  exit 4
else
  echo "WA ou outros"
  exit 6
fi